source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'capybara'
gem 'clearance'
gem 'factory_girl_rails'
gem 'rspec-rails'
gem 'shoulda-matchers'
gem 'simple_form'
gem 'sqlite3'
gem 'strong_parameters'
