source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '7.0.8'

gem 'clearance'
gem 'simple_form'
gem 'sqlite3'
gem 'sprockets-rails'
gem 'puma'
gem 'importmap-rails'
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'bootsnap', require: false

group :development, :test do
  gem 'bourne', '1.3.0'
  gem 'foreman'
  gem 'rspec-rails'
  gem 'rails-dom-testing'
  gem 'listen'
end

group :test do
  gem 'capybara'
  gem 'email_spec'
  gem 'factory_bot_rails'
  gem 'shoulda-matchers'
end
